// <auto-generated />
using System;
using BlazorApp1.Server.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorApp1.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230705082642_addedMainFormyo")]
    partial class addedMainFormyo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("BlazorApp1.Shared.Form", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("dateCreated")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Forms");
                });

            modelBuilder.Entity("BlazorApp1.Shared.IndividualMultichoiceQuestion", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("QuestionID");

                    b.ToTable("individualMultiChoiceQuestion");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FormID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("question")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("FormID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("BlazorApp1.Shared.mainform", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentMainform")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("MainForm");
                });

            modelBuilder.Entity("BlazorApp1.Shared.IndividualMultichoiceQuestion", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Question", null)
                        .WithMany("listOfMultiChoiceQuestions")
                        .HasForeignKey("QuestionID");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Question", b =>
                {
                    b.HasOne("BlazorApp1.Shared.Form", null)
                        .WithMany("QuestionList")
                        .HasForeignKey("FormID");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Form", b =>
                {
                    b.Navigation("QuestionList");
                });

            modelBuilder.Entity("BlazorApp1.Shared.Question", b =>
                {
                    b.Navigation("listOfMultiChoiceQuestions");
                });
#pragma warning restore 612, 618
        }
    }
}
